---
- name: deploy ec2 instance
  ec2_instance:
    name: "pcb311.hackathon2019.nmetech.com"
    state: present
    image_id: ami-0b69ea66ff7391e80
    instance_type: t3.small
    key_name: "nick-hackathon2019"
    region: us-east-1
    security_group: sg-86b045d6
    vpc_subnet_id: subnet-6ec10c23
    network:
      assign_public_ip: true
    volumes:
    - device_name: /dev/xvda
      ebs:
        delete_on_termination: true
        volume_size: 50
    user_data: |
               #!/bin/sh
               sudo yum install -y python3
    tags:
      Activity: PBC311
      Environment: Production
      Owner: nick
  register: ec2_instance_pbc311

- name: create ec2 eip
  ec2_eip:
    device_id: "{{ ec2_instance_pbc311.instances.0.instance_id }}"
    region: us-east-1
  register: ec2_eip_pbc311

- name: deploy rds instance
  rds:
    command: create
    instance_name: pbc311
    db_engine: postgres
    size: "10"
    instance_type: db.t3.micro
    region: us-east-1
    username: pgadmin
    password: cat4life
    tags:
      Activity: PBC311
      Environment: Production
      Owner: nick
  register: rds_instance_pbc311

- name: setup public dns - ec2
  route53:
    state: present
    zone: hackathon2019.nmetech.com
    private_zone: no
    record: pbc311.hackathon2019.nmetech.com
    type: A
    ttl: 60
    value:
      - "{{ ec2_eip_pbc311.public_ip }}"
    overwrite: yes
    wait: yes

- name: setup private dns - ec2
  route53:
    state: present
    zone: hackathon2019.nmetech.com
    private_zone: yes
    record: pbc311.hackathon2019.nmetech.com
    type: A
    ttl: 60
    value:
      - "{{ ec2_instance_pbc311.instances.0.private_ip_address }}"
    overwrite: yes
    wait: yes

- name: setup public dns - db
  route53:
    state: present
    zone: hackathon2019.nmetech.com
    private_zone: no
    record: pbc311-db.hackathon2019.nmetech.com
    type: CNAME
    ttl: 60
    value:
      - "{{ rds_instance_pbc311.instance.endpoint }}"
    overwrite: yes
    wait: yes

- name: setup private dns - db
  route53:
    state: present
    zone: hackathon2019.nmetech.com
    private_zone: yes
    record: pbc311-db.hackathon2019.nmetech.com
    type: CNAME
    ttl: 60
    value:
      - "{{ rds_instance_pbc311.instance.endpoint }}"
    overwrite: yes
    wait: yes
