---
- name: configure and deploy the infrastructure
  hosts: local
  roles:
    - deploy-iaas

- name: setup web server
  hosts: pbc311
  roles:
    - provision-users
    - setup-postgres
    - setup-nginx
