---
- name: install nginx
  shell: sudo amazon-linux-extras install -y nginx1.12
  ignore_errors: True

- name: start nginx
  service:
    name: nginx
    state: started
  become: yes

- name: autostart nginx
  systemd:
    name: nginx
    enabled: yes
  become: yes

- name: setup cert deps
  shell: sudo amazon-linux-extras install -y epel

- name: install certbot
  shell: sudo yum install -y certbot python2-certbot-nginx

- name: create cert
  shell: |
    set timeout 300
    certbot-auto certonly \
      --agree-tos \
      --non-interactive \
      --text \
      --rsa-key-size 4096 \
      --email nick@nmetech.com \
      --webroot-path /var/www/html \
      --domains "hackathon2019.nmetech.com"
  become: yes

- name: config nginx
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  become: yes
