---
- name: install postgres 10
  shell: sudo amazon-linux-extras install postgresql10
  ignore_errors: True

- name: install postgresql-devel
  shell: sudo yum install -y postgresql-devel

- name: install dev toolkit
  shell: sudo yum groupinstall -y "Development Tools"

- name: install python3-dev
  shell: sudo yum install -y python3-devel

- name: install pip3
  shell: sudo yum install -y python3-pip

- name: install psycopg2
  pip:
    name: psycopg2
    executable: pip3
    state: latest
  become: yes

- name: setup postgres stored credentials
  template: src=.pgpass dest=~/.pgpass

- name: write db seed file
  template: src=create_tables.py dest=~/create_tables.py

- name: seed database
  shell: python3 create_tables.py
