---
- name: install postgres 10
  shell: sudo amazon-linux-extras install -y postgresql10
  ignore_errors: True

- name: install postgresql-devel
  shell: sudo yum install -y postgresql-devel

- name: install dev toolkit
  shell: sudo yum groupinstall -y "Development Tools"

- name: setup postgres stored credentials
  template:
    src: .pgpass
    dest: ~/.pgpass
    mode: '0600'

- name: Create a new database with name "pbc311"
  postgresql_db:
    name: pbc311
    login_host: pbc311-db.hackathon2019.nmetech.com
    login_user: pgadmin
    login_password: "{{ postgres_pw }}"

- name: write db seed file
  template: src=create_tables.py dest=~/create_tables.py

- name: seed database
  shell: python3 create_tables.py
